apiVersion: apps/v1
kind: Deployment
metadata: 
  name: startbux-deploy
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: startbux
  template:
    metadata:
      labels: 
        app: startbux
spec:
  containers:
  - name: startbux
    image: gariptipici/starbux:0.0.1
    ports: 
    - containerPort: 80
