apiVersion: apps/v1
kind: Deployment
metadata: 
  name: startbux-deploy
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: startbux
  template:
    metadata:
      labels: 
        app: startbux
    spec:
      containers:
       - name: startbux
         image: nginx:stable-alpine3.23-perl
         ports: 
         - containerPort: 80
